### ISSUE TITLE
Can't boot pre-built image on Galileo Gen 2

### ISSUE THREAD

**Issue by pksm** [ostroproject/ostro-os#98] opened 2016-05-13 12:47 UTC
When trying to boot from **ostro-image-noswupd-intel-quark-2016-05-02_00-09-47-build-440.dsk** , **ostro-image-noswupd-intel-quark.dsk** or **ostro-image-swupd-dev-intel-quark.dsk**, the process hangs on this point:
     JBD2: no valid journal superblock found 
     EXT4-fs (mmcblk0p3): error loading journal

Log from boot process is attached.
[bootLog.txt](https://github.com/ostroproject/ostro-os/files/263280/bootLog.txt)

**Comment by kad** [comment] 2016-05-13 13:01
How did you flash image to uSD card ?
Have you checked that download for uncompressed dsk file completed successfully ?

**Comment by pksm** [comment] 2016-05-13 13:11
All of quoted images were **.dsk.xz** and they all downloaded and uncompressed successfully (sorry I think a cut out the xz part on my previous post).

I've flashed multiple times in different OSes. On Windows I used 7zip (for extration) and  win32diskimager. And on Debian 8.4 I followed the guide on Ostro's documentation. 
`$ xzcat <ostro-os-image.dsk.xz> | sudo dd of=/dev/sdb bs=512k` 
`$ sync`

**Comment by gvancuts** [comment] 2016-05-18 10:32
I'm unable to reproduce this at all. Can you double-check that the sha256sum of the images you have downloaded match what's posted on our download website (https://download.ostroproject.org/releases/ostro-os/milestone/v1.0.0/images/intel-quark/)?

It looks like some sort of corruption but it's hard to confirm (or even guess when it's happening).

Could you try with a bigger (16GB) SD card too?

**Comment by pksm** [comment] 2016-05-20 16:45
Hi Geoffroy,
I was able to successfully run an Ostro image on Galileo, but just when I switched to a class 10 8GB sdCard from Kingston. (In my original post, I tested with two class 4 8GB sdCards from SanDisk). 
Do you think this was causing the failure? Unfortunately I don't have other class 4 sdCard to prove this "theory". 
Could you tell me what is the class of your sdCard?

**Comment by gvancuts** [comment] 2016-05-23 12:08
The SD Card I have used so far is class 10. I have just found a class 4, 8GB SD card and will try it out now. I'll keep you posted.

**Comment by gvancuts** [comment] 2016-05-23 12:26
i have just flashed my 4GB SD card (class 4) with https://download.ostroproject.org/releases/ostro-os/milestone/v1.0.0/images/intel-quark/ostro-image-swupd-intel-quark-2016-05-02_00-09-47-build-440.dsk.zip (using bmaptool) and it booted correctly on my Galileo Gen 2 board.

Not sure what is happening with your SD cards, maybe they have too many bad areas?

I searched a bit more and came across this post which describes a problem similar to yours: http://superuser.com/questions/598349/how-can-i-test-the-full-capacity-of-an-sd-card-in-linux

One of their recommendation is to use the F3 tool: http://oss.digirati.com.br/f3/

Let us know if that gives any extra clue as to why it's failing with some of your cards.

**Comment by pksm** [comment] 2016-05-23 13:27
Thanks Geoffroy for the help. I'll test them now and will keep you update.

2016-05-23 9:26 GMT-03:00 Geoffroy Van Cutsem <notifications@github.com>:

**Comment by pksm** [comment] 2016-05-27 21:52
Sorry for the late response. I did the F3 test and my sdcard failed!
So I bought a new 8GB class4 sdcard and it worked! I think my other two
cards weren't bought from a good vendor, they are probably fake.

One last thing I would like to ask you... Does Ostro-OS have a package
manager (like opkg in most yocto images)? If not, how should I add packages
to it?

Thank you

2016-05-23 10:27 GMT-03:00 Paula Moraes <paulamoraes95@gmail.com>:

**Comment by gvancuts** [comment] 2016-05-30 11:47
Hi @pksm , thanks for the update, it sounds like we can close this ticket then.

We do not have a package manager in the traditional sense of the term, instead Ostro implements a SW update mechanism (swupd) that has the notion of bundles. Here are some good starting points on the topic:
* https://ostroproject.org/documentation/architecture/software-update.html
* https://ostroproject.org/documentation/howtos/software-update-server.html

You will certainly notice that we only create two bundles at this stage: os-core and world-dev. The first one is the core OS (you cannot remove it) and the second one has *all* the dev tools. It's of course possible to define finer-grain bundles as described in the docs listed above, but that is left to Ostro users to decide how they want to create their OS.

Thanks

**Comment by mythi** [comment] 2016-08-31 06:12
Based on the comments this one can be closed.

**Closed by mythi** 2016-08-31 06:12 UTC
